spring:
  datasource:
    url: jdbc:mariadb://mariadb-service:3306/todo
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  hikari:
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    autoCommit: false
    maximumPoolSize: 10

  logging:
    level:
      org.mariadb.jdbc: TRACE
